#!/usr/bin/env bash
set -euo pipefail

STAGED_MEMORY_ARM=${STAGED_MEMORY_ARM:-on}
STAGE_PLAN_MANIFEST=${STAGE_PLAN_MANIFEST:?Set STAGE_PLAN_MANIFEST to the frozen staged manifest}
EPISODE_KEYS=${EPISODE_KEYS:-2azQ1b91cZZ:10,2azQ1b91cZZ:11,2azQ1b91cZZ:12,2azQ1b91cZZ:16,2azQ1b91cZZ:70,2azQ1b91cZZ:1393}
RUN_TIMESTAMP=${RUN_TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}

case "${STAGED_MEMORY_ARM}" in
  on)
    QWEN_ABLATION_PROFILE=staged_memory_on
    ;;
  off)
    QWEN_ABLATION_PROFILE=staged_memory_off
    ;;
  *)
    echo "STAGED_MEMORY_ARM must be on or off" >&2
    exit 2
    ;;
esac

export QWEN_ABLATION_PROFILE
export OPENCLAW_STAGE_PLAN_MANIFEST_PATH="${STAGE_PLAN_MANIFEST}"
export OPENCLAW_STAGED_SHADOW_MANIFEST_PATH=${OPENCLAW_STAGED_SHADOW_MANIFEST_PATH:-}
export OPENCLAW_STAGED_MEMORY_EVENT_CAP=${OPENCLAW_STAGED_MEMORY_EVENT_CAP:-64}
export OPENCLAW_STAGED_RECOVERY_RETRIGGER_STEPS=${OPENCLAW_STAGED_RECOVERY_RETRIGGER_STEPS:-3}
export OPENCLAW_STAGE_MIN_TRANSLATION_M=${OPENCLAW_STAGE_MIN_TRANSLATION_M:-0.25}
export OPENCLAW_STAGE_MIN_HEADING_CHANGE_DEG=${OPENCLAW_STAGE_MIN_HEADING_CHANGE_DEG:-15}
export EPISODE_KEYS
export HARNESS_DEBUG_MAX_EPISODES=${HARNESS_DEBUG_MAX_EPISODES:-6}
export OUTPUT_PATH=${OUTPUT_PATH:-results/qwen_staged_memory_${STAGED_MEMORY_ARM}_${RUN_TIMESTAMP}}

exec bash scripts/run_qwen.sh
