#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
cd "${REPO_ROOT}"

RUN_TIMESTAMP=${RUN_TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}
MODEL_PATH=${MODEL_PATH:-/ssd/dingmuhe/Embodied-task/JanusVLN/JanusVLN_Model/misstl/JanusVLN_Extra}
DATA_PATH=${DATA_PATH:-/ssd/dingmuhe/Embodied-task/JanusVLN/data/datasets/r2r/val_unseen/val_unseen.json.gz}
EPISODE_KEYS=${EPISODE_KEYS:-2azQ1b91cZZ:1525,2azQ1b91cZZ:179,2azQ1b91cZZ:980,2azQ1b91cZZ:44,2azQ1b91cZZ:511}
HARNESS_DEBUG_MAX_EPISODES=${HARNESS_DEBUG_MAX_EPISODES:-5}

MODE=${MODE:-no_seed_diagnostic}
GPU=${GPU:-7}
PORT=${PORT:-8024}
MASTER_PORT=${MASTER_PORT:-20627}
MAX_STEPS=${MAX_STEPS:-340}
OUTPUT_PATH=${OUTPUT_PATH:-results/demo_visual_readback_video_keyframes_2az_long5_${RUN_TIMESTAMP}}

SAVE_VIDEO=${SAVE_VIDEO:-1}
SAVE_VIDEO_RATIO=${SAVE_VIDEO_RATIO:-1}
SAVE_STEP_ARTIFACTS=${SAVE_STEP_ARTIFACTS:-0}

OPENCLAW_MODEL_MAX_IMAGES=${OPENCLAW_MODEL_MAX_IMAGES:-2}
OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS=${OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS:-20}
OPENCLAW_AGENT_TIMEOUT=${OPENCLAW_AGENT_TIMEOUT:-90}
OPENCLAW_AGENT_MAX_INPUT_TOKENS=${OPENCLAW_AGENT_MAX_INPUT_TOKENS:-50000}
GATEWAY_TIMEOUT_S=${GATEWAY_TIMEOUT_S:-300}

echo "run_timestamp=${RUN_TIMESTAMP}"
echo "model_path=${MODEL_PATH}"
echo "data_path=${DATA_PATH}"
echo "episode_keys=${EPISODE_KEYS}"
echo "max_episodes=${HARNESS_DEBUG_MAX_EPISODES}"
echo "gpu=${GPU}"
echo "port=${PORT}"
echo "master_port=${MASTER_PORT}"
echo "max_steps=${MAX_STEPS}"
echo "output_path=${OUTPUT_PATH}"
echo "save_video=${SAVE_VIDEO}"
echo "save_step_artifacts=${SAVE_STEP_ARTIFACTS}"

MODE="${MODE}" \
RUN_TIMESTAMP="${RUN_TIMESTAMP}" \
OUTPUT_PATH="${OUTPUT_PATH}" \
MODEL_PATH="${MODEL_PATH}" \
DATA_PATH="${DATA_PATH}" \
GPU="${GPU}" \
PORT="${PORT}" \
MASTER_PORT="${MASTER_PORT}" \
MAX_STEPS="${MAX_STEPS}" \
EPISODE_KEYS="${EPISODE_KEYS}" \
HARNESS_DEBUG_MAX_EPISODES="${HARNESS_DEBUG_MAX_EPISODES}" \
SAVE_VIDEO="${SAVE_VIDEO}" \
SAVE_VIDEO_RATIO="${SAVE_VIDEO_RATIO}" \
SAVE_STEP_ARTIFACTS="${SAVE_STEP_ARTIFACTS}" \
OPENCLAW_MODEL_MAX_IMAGES="${OPENCLAW_MODEL_MAX_IMAGES}" \
OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS="${OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS}" \
OPENCLAW_AGENT_TIMEOUT="${OPENCLAW_AGENT_TIMEOUT}" \
OPENCLAW_AGENT_MAX_INPUT_TOKENS="${OPENCLAW_AGENT_MAX_INPUT_TOKENS}" \
GATEWAY_TIMEOUT_S="${GATEWAY_TIMEOUT_S}" \
bash scripts/run_visual_readback_runtime_smoke.sh
