#!/usr/bin/env bash
set -euo pipefail

RUN_TIMESTAMP=${RUN_TIMESTAMP:-demo_2az_phase3_action_override_$(date +%Y%m%d_%H%M%S)}
OUTPUT_PATH=${OUTPUT_PATH:-results/demo_visual_readback_phase3_action_override_2az_7ep_${RUN_TIMESTAMP}}
MAX_STEPS=${MAX_STEPS:-400}
GPU=${GPU:-7}
PORT=${PORT:-8025}
MASTER_PORT=${MASTER_PORT:-20628}
REUSE_GATEWAY=${REUSE_GATEWAY:-1}

# Fixed targeted set for the Phase 2/3 keyframe readback run.
#EPISODE_KEYS="2azQ1b91cZZ:70,2azQ1b91cZZ:1393,2azQ1b91cZZ:1159,2azQ1b91cZZ:160,2azQ1b91cZZ:778,2azQ1b91cZZ:1756,2azQ1b91cZZ:76"
EPISODE_KEYS="2azQ1b91cZZ:10,2azQ1b91cZZ:12,2azQ1b91cZZ:16,2azQ1b91cZZ:43,\
2azQ1b91cZZ:70,2azQ1b91cZZ:78,2azQ1b91cZZ:79,2azQ1b91cZZ:117,2azQ1b91cZZ:193,\
2azQ1b91cZZ:263,2azQ1b91cZZ:45,2azQ1b91cZZ:76,2azQ1b91cZZ:88,2azQ1b91cZZ:116,\
2azQ1b91cZZ:122,2azQ1b91cZZ:160,2azQ1b91cZZ:168,2azQ1b91cZZ:215,2azQ1b91cZZ:267,2azQ1b91cZZ:277"

HARNESS_DEBUG_MAX_EPISODES=20

# Phase 3 low-config default: Qwen readback can directly override the final
# action through a gated recommended_action. For Phase 2 replan-prompt testing,
# run with OPENCLAW_VISUAL_READBACK_MODE=image_read_replan_prompt.
OPENCLAW_VISUAL_READBACK_MODE=${OPENCLAW_VISUAL_READBACK_MODE:-image_read_action_override}
OPENCLAW_VISUAL_READBACK_TRIGGER_POLICY=${OPENCLAW_VISUAL_READBACK_TRIGGER_POLICY:-sparse_action_override}
OPENCLAW_VISUAL_READBACK_MAX_ACTION_OVERRIDES_PER_EPISODE=${OPENCLAW_VISUAL_READBACK_MAX_ACTION_OVERRIDES_PER_EPISODE:-adaptive}

RUN_TIMESTAMP="${RUN_TIMESTAMP}" \
OUTPUT_PATH="${OUTPUT_PATH}" \
MAX_STEPS="${MAX_STEPS}" \
GPU="${GPU}" \
PORT="${PORT}" \
MASTER_PORT="${MASTER_PORT}" \
REUSE_GATEWAY="${REUSE_GATEWAY}" \
HARNESS_DEBUG_MAX_EPISODES="${HARNESS_DEBUG_MAX_EPISODES}" \
EPISODE_KEYS="${EPISODE_KEYS}" \
OPENCLAW_VISUAL_READBACK_MODE="${OPENCLAW_VISUAL_READBACK_MODE}" \
OPENCLAW_VISUAL_READBACK_TRIGGER_POLICY="${OPENCLAW_VISUAL_READBACK_TRIGGER_POLICY}" \
OPENCLAW_VISUAL_READBACK_MAX_ACTION_OVERRIDES_PER_EPISODE="${OPENCLAW_VISUAL_READBACK_MAX_ACTION_OVERRIDES_PER_EPISODE}" \
OPENCLAW_KEYFRAME_POLICY_MODE="${OPENCLAW_KEYFRAME_POLICY_MODE:-event_gated_smoke}" \
OPENCLAW_KEYFRAME_MIN_GAP_STEPS="${OPENCLAW_KEYFRAME_MIN_GAP_STEPS:-5}" \
OPENCLAW_KEYFRAME_EPISODE_CAP="${OPENCLAW_KEYFRAME_EPISODE_CAP:-64}" \
OPENCLAW_KEYFRAME_COVERAGE_GAP_STEPS="${OPENCLAW_KEYFRAME_COVERAGE_GAP_STEPS:-20}" \
bash scripts/run_visual_readback_demo_2az_long5.sh
