#!/usr/bin/env bash
set -euo pipefail

export OPENCLAW_KILL_EXISTING_GATEWAY=1
export OPENCLAW_STAGED_VISUAL_MEMORY_ENABLED=1
export OPENCLAW_STAGED_MEMORY_TREATMENT=on
export OPENCLAW_DYNAMIC_VISUAL_CONTEXT_ENABLED=1
export OPENCLAW_QWEN_OUTPUT_SCHEMA=route_v3_staged
export OPENCLAW_MODEL=qwen/qwen3.5-flash-2026-02-23
export OPENCLAW_MODEL_FAST_MODE=off
export OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS=1
export OPENCLAW_QWEN_THINKING_MODE=on
export OPENCLAW_QWEN_THINKING_INTERVAL_STEPS=10
export OPENCLAW_QWEN_THINKING_BUDGET=1024
export OPENCLAW_QWEN_TRANSPORT_MODE=sync
export OPENCLAW_QWEN_API_RETRIES=2
export OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18151}"
export OPENCLAW_EVAL_GATEWAY_TIMEOUT=660
export OPENCLAW_ADAPTER_HEALTH_TIMEOUT=30
export OPENCLAW_MAP_ASSIST_MODE=floorplan_map_assisted
export OPENCLAW_MAP_FRAME_INTERVAL_STEPS=1
export OPENCLAW_KEYFRAME_MIN_GAP_STEPS=1
export OPENCLAW_KEYFRAME_COVERAGE_GAP_STEPS=1
export OPENCLAW_MOTION_FEEDBACK_ENABLED=1
export OPENCLAW_FORWARD_STALL_ODOMETRY_ENABLED=1
export OPENCLAW_MAP_COLLISION_OVERLAY_ENABLED=1
export OPENCLAW_CONTROLLER_DISTANCE_EARLY_STOP_M=0
#export EPISODE_KEYS="${EPISODE_KEYS:-2azQ1b91cZZ:10,2azQ1b91cZZ:11,2azQ1b91cZZ:16,2azQ1b91cZZ:70,2azQ1b91cZZ:1393}"

#export EPISODE_KEYS="2azQ1b91cZZ:1159,2azQ1b91cZZ:160,2azQ1b91cZZ:778,2azQ1b91cZZ:1756,2azQ1b91cZZ:76,2azQ1b91cZZ:71,2azQ1b91cZZ:72,2azQ1b91cZZ:45"

export EPISODE_KEYS="2azQ1b91cZZ:1816,2azQ1b91cZZ:271,2azQ1b91cZZ:1088,2azQ1b91cZZ:216,2azQ1b91cZZ:394,2azQ1b91cZZ:366,2azQ1b91cZZ:167"
export HARNESS_DEBUG_MAX_EPISODES=7
export MAX_STEPS=400
export OUTPUT_PATH="results/qwen_staged_5ep_400step_$(date +%Y%m%d_%H%M)"
export CUDA_VISIBLE_DEVICES=0

printf 'run_qwen2 gateway port: %s (kill existing: %s)\n' \
  "${OPENCLAW_GATEWAY_PORT}" "${OPENCLAW_KILL_EXISTING_GATEWAY}"
printf 'run_qwen2 max steps per episode: %s\n' "${MAX_STEPS}"
printf 'run_qwen2 output path: %s\n' "${OUTPUT_PATH}"

exec bash scripts/run_qwen.sh
