#!/usr/bin/env bash
set -euo pipefail

HOST=${HOST:-127.0.0.1}
PORT=${PORT:-8011}
RECALL_INTERVAL_STEPS=${RECALL_INTERVAL_STEPS:-5}
OPENCLAW_GATEWAY_WS_URL=${OPENCLAW_GATEWAY_WS_URL:-}
OPENCLAW_GATEWAY_TIMEOUT=${OPENCLAW_GATEWAY_TIMEOUT:-5}
OPENCLAW_PLANNER_MODE=${OPENCLAW_PLANNER_MODE:-agent}
OPENCLAW_AGENT_ID=${OPENCLAW_AGENT_ID:-main}
OPENCLAW_AGENT_TIMEOUT=${OPENCLAW_AGENT_TIMEOUT:-180}
OPENCLAW_AGENT_MAX_INPUT_TOKENS=${OPENCLAW_AGENT_MAX_INPUT_TOKENS:-10000}
OPENCLAW_PROFILE=${OPENCLAW_PROFILE:-}
OPENCLAW_MODEL=${OPENCLAW_MODEL:-qwen/qwen3.5-flash}
OPENCLAW_MODEL_PROVIDER=${OPENCLAW_MODEL_PROVIDER:-qwen_api}
OPENCLAW_MODEL_MAX_IMAGES=${OPENCLAW_MODEL_MAX_IMAGES:-3}
OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS=${OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS:-20}
OPENCLAW_MODEL_FAST_MODE=${OPENCLAW_MODEL_FAST_MODE:-qwen_text_only}
OPENCLAW_MODEL_FAST_USE_MEMORY_CONTEXT=${OPENCLAW_MODEL_FAST_USE_MEMORY_CONTEXT:-1}
OPENCLAW_MODEL_MEMORY_POLICY_MODE=${OPENCLAW_MODEL_MEMORY_POLICY_MODE:-raw}
OPENCLAW_MODEL_FILTER_STOP_SEMANTICS=${OPENCLAW_MODEL_FILTER_STOP_SEMANTICS:-0}
OPENCLAW_VISUAL_MODE=${OPENCLAW_VISUAL_MODE:-path}
OPENCLAW_VISUAL_MAX_IMAGES=${OPENCLAW_VISUAL_MAX_IMAGES:-2}
OPENCLAW_VISUAL_INTERVAL_STEPS=${OPENCLAW_VISUAL_INTERVAL_STEPS:-1}
OPENCLAW_VISUAL_TIMEOUT_MS=${OPENCLAW_VISUAL_TIMEOUT_MS:-90000}
OPENCLAW_VISUAL_MODEL=${OPENCLAW_VISUAL_MODEL:-qwen/qwen3.5-flash}

cd "$(dirname "$0")/.."

args=(
  --host "${HOST}"
  --port "${PORT}"
  --recall_interval_steps "${RECALL_INTERVAL_STEPS}"
  --timeout "${OPENCLAW_GATEWAY_TIMEOUT}"
  --planner_mode "${OPENCLAW_PLANNER_MODE}"
  --agent_id "${OPENCLAW_AGENT_ID}"
  --agent_timeout "${OPENCLAW_AGENT_TIMEOUT}"
  --agent_max_input_tokens "${OPENCLAW_AGENT_MAX_INPUT_TOKENS}"
  --openclaw_model "${OPENCLAW_MODEL}"
  --openclaw_model_provider "${OPENCLAW_MODEL_PROVIDER}"
  --openclaw_model_max_images "${OPENCLAW_MODEL_MAX_IMAGES}"
  --openclaw_model_image_interval_steps "${OPENCLAW_MODEL_IMAGE_INTERVAL_STEPS}"
  --openclaw_model_fast_mode "${OPENCLAW_MODEL_FAST_MODE}"
  --openclaw_model_fast_use_memory_context "${OPENCLAW_MODEL_FAST_USE_MEMORY_CONTEXT}"
  --openclaw_model_memory_policy_mode "${OPENCLAW_MODEL_MEMORY_POLICY_MODE}"
  --openclaw_model_filter_stop_semantics "${OPENCLAW_MODEL_FILTER_STOP_SEMANTICS}"
  --openclaw_visual_mode "${OPENCLAW_VISUAL_MODE}"
  --openclaw_visual_max_images "${OPENCLAW_VISUAL_MAX_IMAGES}"
  --openclaw_visual_interval_steps "${OPENCLAW_VISUAL_INTERVAL_STEPS}"
  --openclaw_visual_timeout_ms "${OPENCLAW_VISUAL_TIMEOUT_MS}"
)
if [[ -n "${OPENCLAW_GATEWAY_WS_URL}" ]]; then
  args+=(--openclaw_gateway_url "${OPENCLAW_GATEWAY_WS_URL}")
fi
if [[ -n "${OPENCLAW_PROFILE}" ]]; then
  args+=(--openclaw_profile "${OPENCLAW_PROFILE}")
fi
if [[ -n "${OPENCLAW_VISUAL_MODEL}" ]]; then
  args+=(--openclaw_visual_model "${OPENCLAW_VISUAL_MODEL}")
fi

PYTHONPATH=src /ssd/dingmuhe/anaconda3/envs/janusvln/bin/python \
  -m harness.openclaw.openclaw_cli_plan_gateway \
  "${args[@]}"
